name: Nmap-SSH

on:
  push:
    branches:
      - master

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Instalar nmap
        run: sudo apt-get install -y nmap
      - name: Hacer nmap
        run: nmap -sV mercadona.es -oN nmap_report-Horacio.txt
      - name: Conectar y enviar archivo a servidor SSH
        run: |
          sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no nmap_report-Horacio.txt ${{ secrets.USER }}@${{ secrets.IP }}:~/
