name: SSH

on:
    push:
      branches:
        - master
jobs:
    hola:
      runs-on: ubuntu-latest
      steps:
        - name: Instalamos ssh
          run: sudo apt-get install ssh
        - name: Comprobamos que existe ssh 
          run: ssh -v