name: Add File to Repo

on:
    push:
        branches:
            - master

jobs:
  add-file:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
        
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Instalar Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap
    - name: Usar Nmap
      run: nmap -sV mercadona.es -oN nmap_report.txt
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "acciones@github.com"
        git add nmap_report.txt
        git commit -m "Añadido archivo generado automáticamente"
        git push